Task: Vector (adding two vectors, subtraction and multiplication of two vectors)

Matrx (adding two matrix, subtracting two matrix, and multiplication of two matrix)
Please do it in python and submit the python file on discord


In [1]:
import numpy as np

In [3]:
# 1-D array is a vector
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])

In [5]:
print(f"Sum of Vectors are: {vec1 +vec2}")
print(f"Difference of Vectors are: {vec1 - vec2}")
print(f"Multiplication of Vectors is: {vec1 * vec2}")

Sum of Vectors are: [5 7 9]
Difference of Vectors are: [-3 -3 -3]
Multiplication of Vectors is: [ 4 10 18]


In [6]:
# 2-D array is a matrix
mat1 = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

mat2 = np.array([[10,11,12],
[13,14,15],
[16,17,18]])

In [12]:
print(f"Sum of matrices are: \n {mat1 + mat2}")
print(f"Difference of matrices are: \n {mat1 - mat2}")
print(f"Multiplication of matrices is: \n {np.dot(mat1,mat2)}")

Sum of matrices are: 
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Difference of matrices are: 
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
Multiplication of matrices is: 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
